apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: front-end
    app: nginx
spec:
  replicas: 5
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp
        tier: front-end
    spec:
      containers:
      -  name: nginx
         image: nginx
  selector:
    matchLabels:
      app: myapp
